### ISSUE TITLE
REQUEST: Make show_last_changed available for all entities

### ISSUE THREAD

**Issue by mihalski** [andrey-git/home-assistant-custom-ui#17]
This would be extremely useful for all sorts of sensors (especially motion sensors).

**Comment by andrey-git** [comment]
This is hard to do without core support.
The feature is supported in state cards which I cloned in CustomUI.
Light and Cover are cloned in order to add the slider.
Toggle and Plain are very simple so I cloned them specifically to support CustomUI features.
It doesn't make sense to clone the advanced cards as I would have to follow the upstream changes.

**Comment by mihalski** [comment]
Is not the grey subheading when you go into the details of each state card not available in a consistent way?

I'm referring to:
![image](https://user-images.githubusercontent.com/3755059/27767652-75286848-5f41-11e7-9705-dd4a566b3e52.png)

I think this used to be displayed by default in earlier versions of Home Assistant (well before I started using it, going by screenshots on the web). Seems to be an often requested feature.

**Comment by andrey-git** [comment]
I have added support for `show_last_changed` for all state cards (except Configurator)

**Comment by mihalski** [comment]
Thank you! I'm sure this will be a very popular addition.
