### ISSUE TITLE
complete example has an error in the extra data template?

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#65]
---edit---

this seems to be better:

  ```
extra_data_template: >
    if (attributes.power_consumption) return attributes.power_consumption + 'W'; return null;
```

HI,

example on https://github.com/andrey-git/home-assistant-custom-ui#complete-example 

`extra_data_template: ${attributes.power_consumption !== 0 ? (attributes.power_consumption + 'W') : null}`
seems not to work, as in incorrect syntax, but can't find the solution yet (late, sorry....)
taking out the extra data template line makes it work, so must be that?
Cheers,
Marius

**Comment by andrey-git** [comment]
I have clarified the instructions.
`extra_data_template: ${attributes.power_consumption !== 0 ? (attributes.power_consumption + 'W') : null}` didn't work because yaml parsing didn't like the ":".
`"extra_data_template: ${attributes.power_consumption !== 0 ? (attributes.power_consumption + 'W') : null}"` worked but would return the `'null'` string.
I clarified the instructions that the format without the `return` word always returns a string.

Thank you for the report!
