### ISSUE TITLE
device_tracker state won't customize?

### ISSUE THREAD

**Issue by hvbhome** [andrey-git/home-assistant-custom-ui#97]
hi,
trying to customize the device_tracker i run into an issue of incorrect syntax apparently cause the state isnt used somehow
this works fine
```
device_tracker.hvbdiskstation:
  templates:
    theme: >
      if (state === 'home') return 'green'; else return 'red';
```
this however won't:
```
device_tracker.hvbdiskstation:
  value_template: '{% if is_state("device_tracker.hvbdiskstation", "home") %}Online{% else %}Offline{% endif %}'
```
as won't:

```
device_tracker.hvbdiskstation:
  templates:
    state: if (state === 'home') return 'Active'; else return 'Alert!';
```

or 

```
device_tracker.hvbdiskstation:
  templates:
    state: >
      if (state === 'home') return 'Active'; else return 'Alert!';

```

which should be the correct syntax for changing the return based on the state,

Thanks for your help,
Marius

**Comment by fanaticDavid** [comment]
Hmmm you first non-working example makes no sense to me. `value_template` is only used within the configuration of certain components in Home Assistant. As far as I know, `value_template` cannot be used as a part of `customize:`, and this Custom UI doesn't use it either.

When it comes to your second non-working example, I've had a similar experience. I used:
```yaml
templates:
  state: if (state === 'ONLINE') return 'Online'; else return 'On battery';
```
The result was that the state showed as 'Online' briefly, then switched to 'On battery' and stayed there. The logic (or lack thereof) might be that once your state has changed, the condition can no longer be true (except after restarting Home Assistant maybe, but again the effect would only be short-lived).

My fix was to use `_stateDisplay` instead of `state`:
```yaml
templates:
  _stateDisplay: if (state === 'ONLINE') return 'Online'; else return 'On battery';
```
Andrey's [documentation on templates](https://github.com/andrey-git/home-assistant-custom-ui/blob/master/docs/templates.md#change-on-state-to-activated) shows both your code and mine as examples, implying that both should achieve the same result. However, our experiences seem to say otherwise.

**Comment by hvbhome** [comment]
thank you!
Completely missed that before, and it works beautifully:
both theme green and Online:
![schermafbeelding 2018-02-04 om 00 03 13](https://user-images.githubusercontent.com/33354141/35772437-0386f33c-093f-11e8-871f-0daaea6eab09.jpg)

using:

```
device_tracker.iungo:
  templates:
#    state: if (state === 'home') return 'Active'; else return 'Alert!';
    theme: >
      if (state === 'home') return 'green'; else return 'red';
#    value_template: '{% if is_state("device_tracker.iungo", "home") %}Online{% else %}Offline{% endif %}'
    _stateDisplay: if (state === 'home') return 'Online'; else return 'Offline';

```

About the value_template: that does work fine in the developer tools, template checker <> and was the only syntax i could get to work there.

Thanks again, back to formatting the frontend!
Cheers,
Marius
